import { Course, ContentItem, Payment, TrackOption } from './types';

export const MOCK_CONTENT_ITEMS: Record<string, ContentItem[]> = {
  l1: [
    {
      content_items_id: 'ci-101',
      level_id: 'l1',
      title: 'Lecture 1.1: ARM Cortex-M Architecture & Memory Maps',
      content_type: 'video',
      youtube_id: 'dQw4w9WgXcQ',
      is_free: true,
      order_no: 1,
    },
    {
      content_items_id: 'ci-102',
      level_id: 'l1',
      title: 'Lab Manual: STM32 GPIO Register Configuration (PDF)',
      content_type: 'drive',
      drive_file_id: '1a2b3c4d5e6f7g8h9i0j',
      url: 'https://drive.google.com/file/d/1a2b3c4d5e6f7g8h9i0j/view',
      is_free: false,
      order_no: 2,
    },
    {
      content_items_id: 'ci-103',
      level_id: 'l1',
      title: 'Starter Code Repository (GitHub)',
      content_type: 'code',
      url: 'https://github.com/itvate-solutions/stm32-bare-metal-template',
      is_free: false,
      order_no: 3,
    },
  ],
  l2: [
    {
      content_items_id: 'ci-201',
      level_id: 'l2',
      title: 'Lecture 2.1: I2C & SPI Protocol Timing Diagrams',
      content_type: 'video',
      youtube_id: 'dQw4w9WgXcQ',
      is_free: false,
      order_no: 1,
    },
    {
      content_items_id: 'ci-202',
      level_id: 'l2',
      title: 'Logic Analyzer Capture Files (.sal)',
      content_type: 'drive',
      drive_file_id: '2b3c4d5e6f7g8h9i0j1a',
      url: 'https://drive.google.com/file/d/2b3c4d5e6f7g8h9i0j1a/view',
      is_free: false,
      order_no: 2,
    },
  ],
};

export const MOCK_COURSES: Course[] = [
  {
    course_id: 'c1',
    name: 'Embedded Systems & Firmware Engineering',
    slug: 'embedded-systems-firmware',
    description: 'Master C/C++, ARM Cortex Microcontrollers, FreeRTOS, and Hardware Interfacing from bare-metal to OS level.',
    is_active: true,
    category: 'Hardware Engineering',
    levels: [
      {
        level_id: 'l1',
        course_id: 'c1',
        no: 1,
        level_title: 'Level 1: C/C++ Bare Metal Programming & GPIO',
        level_description: 'Registers, Memory Maps, Clocks, Interrupts',
        price: 150,
        code: 'EMB-L1',
        is_active: true,
        year: 2026,
        content_items: MOCK_CONTENT_ITEMS.l1,
      },
      {
        level_id: 'l2',
        course_id: 'c1',
        no: 2,
        level_title: 'Level 2: Peripherals (I2C, SPI, UART, Timers, ADC)',
        level_description: 'Protocol drivers and sensor integration',
        price: 200,
        code: 'EMB-L2',
        is_active: true,
        year: 2026,
        content_items: MOCK_CONTENT_ITEMS.l2,
      },
      {
        level_id: 'l3',
        course_id: 'c1',
        no: 3,
        level_title: 'Level 3: FreeRTOS & Real-Time OS Architecture',
        level_description: 'Mutexes, Semaphores, Queues & Task Scheduling',
        price: 250,
        code: 'EMB-L3',
        is_active: true,
        year: 2026,
      },
    ],
  },
  {
    course_id: 'c2',
    name: 'Industrial IoT & Edge Intelligence',
    slug: 'industrial-iot-edge-ai',
    description: 'Build enterprise-grade IoT gateways, MQTT/HTTP protocols, ESP32/Linux edge nodes, and cloud connectivity.',
    is_active: true,
    category: 'Internet of Things',
    levels: [
      {
        level_id: 'l4',
        course_id: 'c2',
        no: 1,
        level_title: 'Level 1: Edge Sensors & Wireless Communications',
        level_description: 'ESP32, BLE, Wi-Fi, LoRaWAN fundamentals',
        price: 180,
        code: 'IOT-L1',
        is_active: true,
        year: 2026,
      },
      {
        level_id: 'l5',
        course_id: 'c2',
        no: 2,
        level_title: 'Level 2: Industrial Gateways & Cloud Telemetry',
        level_description: 'MQTT Broker setup, TLS Security & AWS IoT Core',
        price: 220,
        code: 'IOT-L2',
        is_active: true,
        year: 2026,
      },
    ],
  },
  {
    course_id: 'c3',
    name: 'PCB Design & High-Speed Hardware Design',
    slug: 'pcb-design-hardware',
    description: 'Comprehensive schematic creation, multi-layer layout, signal integrity, and manufacturing deliverables (Gerbers, BOM).',
    is_active: true,
    category: 'Hardware Design',
    levels: [
      {
        level_id: 'l6',
        course_id: 'c3',
        no: 1,
        level_title: 'Level 1: KiCad Fundamentals & 2-Layer Board Layout',
        level_description: 'Schematic capture, footprints & basic Routing',
        price: 160,
        code: 'PCB-L1',
        is_active: true,
        year: 2026,
      },
      {
        level_id: 'l7',
        course_id: 'c3',
        no: 2,
        level_title: 'Level 2: 4-Layer High-Speed PCB Layout & DFM',
        level_description: 'Impedance matching, Ground planes & Gerber generation',
        price: 240,
        code: 'PCB-L2',
        is_active: true,
        year: 2026,
      },
    ],
  },
];

export const TRACK_OPTIONS: TrackOption[] = [
  {
    id: 'Expert',
    name: 'Expert Track',
    tagline: 'Complete Mastery (All Levels)',
    description: 'Instant full access to all course levels simultaneously. Ideal for experienced engineers aiming for fast full-stack mastery.',
    badge: 'Popular',
    multiplier: 1.0,
  },
  {
    id: 'Progressive',
    name: 'Progressive Track',
    tagline: 'Sequential Step-by-Step',
    description: 'Unlock levels one by one as you complete assessments. Recommended for structured step-by-step learners.',
    multiplier: 1.1,
  },
  {
    id: 'Fast',
    name: 'Fast Track',
    tagline: 'Custom Level Pick',
    description: 'Pick and skip directly to any specific level (e.g. direct Level 3) tailored to your existing knowledge base.',
    multiplier: 1.15,
  },
  {
    id: 'Premium',
    name: 'Premium Track',
    tagline: '1-on-1 Dedicated Mentorship',
    description: 'Includes 1-on-1 live practical code reviews, direct instructor debugging, and custom project guidance.',
    badge: 'VIP',
    multiplier: 1.5,
  },
];

export const MOCK_PENDING_PAYMENTS: (Payment & { user_name: string; user_email: string; course_name: string; track_type: string })[] = [
  {
    payment_id: 'pay-001',
    enroll_id: 'enr-101',
    user_name: 'Muhammad Ali',
    user_email: 'ali.m@example.com',
    course_name: 'Embedded Systems & Firmware Engineering',
    track_type: 'Expert',
    amount: 600,
    discount: 60,
    total_amount: 540,
    payment_method: 'Bank Transfer',
    transaction_reference: 'TRX-998822114',
    status: 'Pending',
    payment_proof: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&auto=format&fit=crop&q=80',
    created_at: '2026-07-26T10:15:00Z',
  },
  {
    payment_id: 'pay-002',
    enroll_id: 'enr-102',
    user_name: 'Sara Khan',
    user_email: 'sara.k@example.com',
    course_name: 'Industrial IoT & Edge Intelligence',
    track_type: 'Premium',
    amount: 400,
    discount: 0,
    total_amount: 400,
    payment_method: 'Bank Transfer',
    transaction_reference: 'HBL-77665544',
    status: 'Pending',
    payment_proof: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=800&auto=format&fit=crop&q=80',
    created_at: '2026-07-26T12:40:00Z',
  },
];
